### PR TITLE
Tnw project

### PR DESCRIPTION
**Pull request by Gracetemitope**
This is a replicate of the https://thenextweb.com/

The following was done in this collaborative project branch:
Linter setup
Header, main content and footer section of the next web page
Positioning and alignment were well redefined.
Responsive design
Appropriate commit messages and good collaboration

Live Link: https://gracetemitope.github.io/TNW-Project/

desktop
mobile

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Invalid :heavy_multiplication_x: 
Hello @Gracetemitope  and @AK-Devil 
I am marking this review as invalid as the project does not have a custom readme.
Please update your readme and request another review.
Thanks
slack(@ebeagusamuel)

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hi team @Gracetemitope  and @AK-Devil 👋  👋 , you guys well in this project 👏 👏 , it looks good.  However, before we can mark it as complete, we need to make a few changes:

- [x] Since this project was based on a mobile-first approach there is no need for a breakpoint for the small screen as base styles are for the mobile screen. ([Screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)).  Kindly change your breakpoints to accommodate the medium version whose breakpoint is ` min-width around 768px`. For the large view, the breakpoint is `
min-width 1024px`

- [x] Let's clean up our CSS by reusing common styles like `display: flex`. To do this, create a class, give it a name like `d-flex` then give the properties `display: flex`. If you need to use `display: flex` you just need to call `display:d-flex` as many times as you wish.

- [x] Check out the following comments i left:

#### Navigation bar

**Large version**

- [x]  It contains main navigation row ([link to page](https://thenextweb.com/)). You are missing the top navbar, kindly add it.

**Check out the screenshot from the original website below**
or

- [x] The search icon at the rightmost side of the sub-navigation row is inverted, kindly compare to the original([link to page](https://thenextweb.com/))

**Check out the screenshot from the clone below**
cl

###### Medium version changes

* [x] TWN logo appears at the leftmost part ([link to page](https://thenextweb.com/))

#### Top 3 articles section

###### Large version
* [x] It contains TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/))
**check out screenshot from original website below**
or


###### Medium version changes
**check out screenshot from original website below**
* [x] TWN logo disappears ([link to page](https://thenextweb.com/))
cl4


#### Latest news section
###### Large version

* [x] It aligns 4 articles per row ([link to page](https://thenextweb.com/))
##### Medium version changes
* [x] It aligns 3 articles per row ([link to page](https://thenextweb.com/))

#### Latest Funding section
###### Medium version changes

* [x] It aligns 3 articles per row ([link to page](https://thenextweb.com/))

##### Categories (Apps, Gear, Tech, etc) section

###### Medium version changes

* [x] It aligns 2 category boxes per row ([link to page](https://thenextweb.com/))

##### Latest deals section

###### Large version

* [x] It aligns 4 deals per row ([link to page](https://thenextweb.com/))

###### Medium version changes

* [x] It aligns 3 deals per row ([link to page](https://thenextweb.com/))

##### Footer

* [x] It contains TNW logo with a copyright paragraph ([link to page](https://thenextweb.com/)). Add the TNW logo.

That's all 😄 , kindly work on the review and submit when you are done.

Happy Coding 🖱️ 

Regards
Peris Ndanu
Feel free to slack me if you need any clarifications

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @Gracetemitope and @AK-Devil, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating thenextweb.com. Kindly fix the following issues.

[REQUIRED]

- [x] The header shouldn't have the TNW logo on large screens

- [x] Fix the top news section on medium screens; it should be the same as the original

- [x] In the "Latest News" section, "Latest Deals" section, and the "Latest Funding" section, articles should be aligned 4, 3, or 1 per row respectively on large, medium, and small screens.

- [x] In the Categories (Apps, Gear, Tech) section, articles should be aligned 3, 2, or 1 per row respectively on large, medium, and small screens.

| Your Copy | Source | 
| :---:  |     :---:   |
|Screen Shot 2020-12-03 at 10 45 06 PM|Screen Shot 2020-12-03 at 11 27 27 PM|
|Screen Shot 2020-12-03 at 10 37 38 PM|Screen Shot 2020-12-03 at 10 37 49 PM|
|Screen Shot 2020-12-03 at 10 58 43 PM|Screen Shot 2020-12-03 at 10 51 51 PM|

Fix the fonts styles and font families to make it similar to the original page

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by ioilmio — CHANGES_REQUESTED** [review]
## Hello @Gracetemitope @AK-Devil 👋🏼 
### You are doing great and the results are showing up you should be proud of you, and your teamwork well done! 👍🏼 

#### We want you to showcase these projects, and master some concepts so let's work on some required changes before your project can get approved;

### Required changes 🔴 
#### This is your top 3 articles section
image
and this is the original one
image

- As you can see the big article has a reddish overlay and the logo is inside it,please remove it from your navbar and add it there together with the overlay; 

## Medium screen size 
- Fix these margin issue, white text is overlapping with red text and it looks pretty messy
image

#Small screen size 
- What happened to the logo? Fix it, please
image

## Small and medium screen size
- Why this white band at the end?
Remove it please
image

### After these changes, you should substitute the screenshots in your readme, and add a better description of the project to it before asking for a new review;

##### For any further info, you can contact me on slack @illuminatosalvatore
##### Happy coding 💻

**Review by ioilmio — CHANGES_REQUESTED** [review]
#### Hello again Team 👋🏼  its' Salvatore, I was so happy to re-review your project and after check it, I was about to approve it but I can't 😭 
#### I know how frustrating is to go back to fix one simple trivial thing, but I beg you to fix this last issue with your logo.

Something is wrong with your mediaqueries breakpoints;
For example don't mix min and max width for the same pixels (e.g 768px)
The result is that you will get a moment where your logo will disappear for a pixel, if you resize the window dynamically;
Please fix this issue.

-  ### 767px and below 👍🏼 
image
-------------------
- ### 768px 👎🏼  (logo disappear)
image
---------------------
- ### 769px to 1023px 👍🏼 (but news is hidden behind the logo 👀 )
image
-----------------------
- ###  1024px 👎🏼  (no logo)
image
------------------------
- ### 1025px to  1074px (logo not placed correctly) 👎🏼 
image
-------------------------
- ### 1075px and higher 👍🏼 
image


### Investigate the issue and solve it! 🔍 
### Is more about the concepts 💡  then the result in this case, so please fix them and request for another review; 

#### As always for further info use slack @illuminatosalvatore

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The *News* menu element still hides behind the TNW logo
image

- [ ] The media queries still don't act as previous TSE suggested please correct that.

### [Comments] :green_circle: 

- Use the media query inspector to observe the changes in the original page and compare it with the project.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:



_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
